import Head from "next/head";
import Card from "../components/Card";
import styled from "styled-components";
import { getAllDays } from "../services/dayService";

export async function getServerSideProps() {
  const days = await getAllDays();

  return {
    props: { days: days },
  };
}

export default function Home({ days }) {
  return (
    <div>
      <Head>
        <title>My Baby</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CardContainer>
          {days.map((day) => (
            <Card
              key={day.id}
              weight={day.weight}
              date={day.date}
              height={day.height}
            />
          ))}
        </CardContainer>
      </main>
    </div>
  );
}

const CardContainer = styled.div`
  display: flex;
  gap: 1em;
  flex-wrap: wrap;
  justify-content: center;
  padding: 1em;
  margin-top: 3.5em;
`;
